<%@ include file="/src/header/module/header.jsp" %>
<html>

<head>
<title>Radiology Information System</title>
</head>

<body>
	<H1>
		<CENTER>Radiology Information System</CENTER>
	</H1>
	
	<%
	//get the logged in users class
	String className = (String) session.getAttribute("class");
	if(className == null){
		out.println("<P><B>Welcome to the Radiology Information System!</B></P>");
		out.println("<P>To login press on the login button in the upper right side of your screen.</P>");
	}
	else{
		String user_name = (String) session.getAttribute("user_name");
		out.println("<P><B>Welcome " + user_name + " to the Radiology Information System!</B></P>");
	}
	%>

	<P>A Radiology Information System (RIS) is a computer information system that stores
	 and processes the information for a radiology lab, including all the data regarding patients,
	 and all medical images generated by various diagnostic and therapeutic equipments, such as X-ray,
	 Computed Tomography (CT/CAT), Ultrasound (US), Magnetic resonance imaging (MRI).
	 This Radiology Information System is optimally complemented with a Picture Archiving and Communication System (PACS).</P>
</body>

</html>